### ISSUE TITLE
FR: Select Middle notes of chord

### ISSUE THREAD

**Issue by X-Raym** [kawaCat/ReaScript-MIDI#5]
Hi :)

So you have select top notes, select bottom notes of chord.. why not a select middle notes of chord ?
 
Could be useful as well (for selecting notes of triads).

**Comment by kawaCat** [comment]
Hi ! :)

Its nicy idea!  I added "MIDI_SelectMiddleNotes.lua" script. this scripts will select notes between  from bottom note to top note . (why will not select one middle note )  because  I could not choose one note in 4th chord  or 5th chord . :p   and if detected notes num as chordTone is less than 2 , nothing will do.maybe

is it working ?

**Comment by X-Raym** [comment]
Seems to works fine ! Excellent ! I use it already !
Question: do you play guitar ?
